# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14dOnvhgc_XMtqrNyFEVDvQ613fugEz0V
"""

import numpy as np
import pandas as pd

# Step 1: Load CSV file (correct path)
data = pd.read_csv("/content/sample_data/sales data analysis.csv")

# Step 2: Convert columns to NumPy arrays
quantity = np.array(data["Quantity"])
unit_price = np.array(data["Unit price"])

# Step 3: Calculate sales
sales = quantity * unit_price

# Step 4: Calculations
print("----- Sales Data Analysis Results -----")
print("Total Sales:", np.sum(sales))
print("Average Sales:", np.mean(sales))
print("Mean:", np.mean(sales))
print("Median:", np.median(sales))
print("Variance:", np.var(sales))
print("Standard Deviation:", np.std(sales))